env: "local"
storage_url: "postgresql://pics:12345678@localhost:8002/pics?sslmode=disable"
http_server:
  url: "localhost:9991"
  timeout: 4s
  idle_timeout: 60s
minio:
  endpoint: "localhost:9000"
  access_key_id: "admin"
  secret_access_key: "password"
  bucket_name: "my-bucket"