env: "local"
minio:
  endpoint: "localhost:9000"
  access_key_id: "admin"
  secret_access_key: "password"
  bucket_name: "my-bucket"
kafka:
  url: "localhost:9092"
  topic: "new-topic"
  group_id: "new-group"